[package]
name = "royalnet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
diesel = { version = "2.2.1", features = ["postgres"] }
log = "0.4.22"
micronfig = "0.3.0"
pretty_env_logger = "0.5.0"
teloxide = { version = "0.12.2", features = ["full"] }
tokio = { version = "1.38.0", features = ["full"] }
