name: "Release new version"

on:
  # Creation of a new tag starting with v
  push:
    tags:
      - "v*"
  # Can also be triggered manually
  workflow_dispatch:

jobs:
  ghcrio:
    uses: Steffo99/.github/.github/workflows/buildrelease-docker.yml@main
